[package]
name = "cosmic-ext-thunderbolt"
version = "0.0.1"
edition = "2024"
license = "GPL-3.0-only"
description = "A Thunderbolt™ applet for the COSMIC™ desktop"
repository = "https://github.com/rdoursenaud/cosmic-ext-thunderbolt"

[features]
mock = []

[build-dependencies]
xdgen = "0.1.0"

[dependencies]
async-stream = "0.3.6"
const_format = "0.2.36"
futures = "0.3.34"
i18n-embed-fl = "0.10.1"
rust-embed = "8.12.0"
serde = { version = "1.0.229", features = ["derive"] }
# tbtools = { git = "https://github.com/intel/tbtools.git", tag = "v0.8.0" }  # Future low level interactions
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.23"
zbus = { version = "5.15.0", default-features = false, features = ["tokio"] }
zvariant = "5.15.0"  # Keep in sync with zbus version. Will not be required once 6.0 is released and adopted.

[dependencies.i18n-embed]
version = "0.16.0"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
# See https://github.com/pop-os/libcosmic/blob/master/Cargo.toml for available features.
features = [
    # Applet support
    "applet",
    "applet-token",
    # Uses cosmic-settings-daemon to watch for config file changes
    "dbus-config",
    # Support creating additional application windows.
    "multi-window",
    # Uses tokio as the executor for the runtime
    "tokio",
    # Add Wayland support to winit
    "wayland",
    # Windowing support for X11, Windows, Mac, & Redox
    "desktop-systemd-scope",
    "winit",
]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
