//! # D-Bus interface proxies for: `org.freedesktop.bolt1.Manager`, `org.freedesktop.bolt1.Power`, `org.freedesktop.bolt1.Device`, `org.freedesktop.bolt1.Domain`
//!
//! This code was generated by `zbus-xmlgen` `5.4.1` from D-Bus introspection data.
//! Source: `org.freedesktop.bolt.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.freedesktop.bolt1.Manager", assume_defaults = true)]
pub trait Manager {
    /// DeviceByUid method
    fn device_by_uid(&self, uid: &str) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// DomainById method
    fn domain_by_id(&self, id: &str) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// EnrollDevice method
    fn enroll_device(
        &self,
        uid: &str,
        policy: &str,
        flags: &str,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// ForgetDevice method
    fn forget_device(&self, uid: &str) -> zbus::Result<()>;

    /// ListDevices method
    fn list_devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// ListDomains method
    fn list_domains(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// DeviceAdded signal
    #[zbus(signal)]
    fn device_added(&self, device: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// DeviceRemoved signal
    #[zbus(signal)]
    fn device_removed(&self, device: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// DomainAdded signal
    #[zbus(signal)]
    fn domain_added(&self, domain: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// DomainRemoved signal
    #[zbus(signal)]
    fn domain_removed(&self, domain: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// AuthMode property
    #[zbus(property)]
    fn auth_mode(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_auth_mode(&self, value: &str) -> zbus::Result<()>;

    /// DefaultPolicy property
    #[zbus(property)]
    fn default_policy(&self) -> zbus::Result<String>;

    /// Generation property
    #[zbus(property)]
    fn generation(&self) -> zbus::Result<u32>;

    /// PowerState property
    #[zbus(property)]
    fn power_state(&self) -> zbus::Result<String>;

    /// Probing property
    #[zbus(property)]
    fn probing(&self) -> zbus::Result<bool>;

    /// SecurityLevel property
    #[zbus(property)]
    fn security_level(&self) -> zbus::Result<String>;

    /// Version property
    #[zbus(property)]
    fn version(&self) -> zbus::Result<u32>;
}
#[proxy(interface = "org.freedesktop.bolt1.Power", assume_defaults = true)]
pub trait Power {
    /// ForcePower method
    fn force_power(&self, who: &str, flags: &str) -> zbus::Result<zbus::zvariant::OwnedFd>;

    /// ListGuards method
    fn list_guards(&self) -> zbus::Result<Vec<(String, String, u32)>>;

    /// State property
    #[zbus(property)]
    fn state(&self) -> zbus::Result<String>;

    /// Supported property
    #[zbus(property)]
    fn supported(&self) -> zbus::Result<bool>;

    /// Timeout property
    #[zbus(property)]
    fn timeout(&self) -> zbus::Result<u32>;
}
#[proxy(interface = "org.freedesktop.bolt1.Device", assume_defaults = true)]
pub trait Device {
    /// Authorize method
    fn authorize(&self, flags: &str) -> zbus::Result<()>;

    /// AuthFlags property
    #[zbus(property)]
    fn auth_flags(&self) -> zbus::Result<String>;

    /// AuthorizeTime property
    #[zbus(property)]
    fn authorize_time(&self) -> zbus::Result<u64>;

    /// ConnectTime property
    #[zbus(property)]
    fn connect_time(&self) -> zbus::Result<u64>;

    /// Domain property
    #[zbus(property)]
    fn domain(&self) -> zbus::Result<String>;

    /// Generation property
    #[zbus(property)]
    fn generation(&self) -> zbus::Result<u32>;

    /// Key property
    #[zbus(property)]
    fn key(&self) -> zbus::Result<String>;

    /// Label property
    #[zbus(property)]
    fn label(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_label(&self, value: &str) -> zbus::Result<()>;

    /// LinkSpeed property
    #[zbus(property)]
    fn link_speed(&self) -> zbus::Result<std::collections::HashMap<String, u32>>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// Parent property
    #[zbus(property)]
    fn parent(&self) -> zbus::Result<String>;

    /// Policy property
    #[zbus(property)]
    fn policy(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_policy(&self, value: &str) -> zbus::Result<()>;

    /// Status property
    #[zbus(property)]
    fn status(&self) -> zbus::Result<String>;

    /// StoreTime property
    #[zbus(property)]
    fn store_time(&self) -> zbus::Result<u64>;

    /// Stored property
    #[zbus(property)]
    fn stored(&self) -> zbus::Result<bool>;

    /// SysfsPath property
    #[zbus(property)]
    fn sysfs_path(&self) -> zbus::Result<String>;

    /// Type property
    #[zbus(property)]
    fn type_(&self) -> zbus::Result<String>;

    /// Uid property
    #[zbus(property)]
    fn uid(&self) -> zbus::Result<String>;

    /// Vendor property
    #[zbus(property)]
    fn vendor(&self) -> zbus::Result<String>;
}
#[proxy(interface = "org.freedesktop.bolt1.Domain", assume_defaults = true)]
pub trait Domain {
    /// BootACL property
    #[zbus(property, name = "BootACL")]
    fn boot_acl(&self) -> zbus::Result<Vec<String>>;
    #[zbus(property, name = "BootACL")]
    fn set_boot_acl(&self, value: &[&str]) -> zbus::Result<()>;

    /// IOMMU property
    #[zbus(property, name = "IOMMU")]
    fn iommu(&self) -> zbus::Result<bool>;

    /// Id property
    #[zbus(property)]
    fn id(&self) -> zbus::Result<String>;

    /// SecurityLevel property
    #[zbus(property)]
    fn security_level(&self) -> zbus::Result<String>;

    /// SysfsPath property
    #[zbus(property)]
    fn sysfs_path(&self) -> zbus::Result<String>;

    /// Uid property
    #[zbus(property)]
    fn uid(&self) -> zbus::Result<String>;
}
